version: '3'
services:
  sandbox:
    build:
      context: ../
      dockerfile: ./sandbox/Dockerfile
    environment:
      - ADMIN_URL=http://127.0.0.1:3000
      - REPO_URL=http://127.0.0.1:7006
    network_mode: 'host'
