services:
  sandbox:
    build:
      context: ../
      dockerfile: ./sandbox/Dockerfile
    environment:
      - ADMIN_URL=${ADMIN_URL}
      - REPO_URL=${REPO_URL}
      - WEB_SANDBOX_SECRET=${WEB_SANDBOX_SECRET}
    network_mode: 'host'
    deploy:
      resources:
        limits:
          cpus: '0.50' # Limit CPU usage to 50%
          memory: 2G
