version: '3'
services:
  sandbox:
    build:
      context: ../
      dockerfile: ./sandbox/Dockerfile
    environment:
      - ADMIN_URL=${ADMIN_URL}
      - REPO_URL=${REPO_URL}
    network_mode: 'host'
