version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=bwcontest
      - POSTGRES_DB=bwcontest
    restart: unless-stopped
  web:
    build:
      context: ../
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
      - 7006:7006
    environment:
      - DATABASE_URL=postgresql://bwcontest:password@db:5432/bwcontest
      - GIT_PORT=7006
      - ORIGIN=http://127.0.0.1:3000
    volumes:
      - ./repo:/app/repo
    depends_on:
      - db
    restart: unless-stopped
