version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=bwcontest
      - POSTGRES_DB=bwcontest
    restart: unless-stopped
  web:
    build:
      context: ../
      dockerfile: ./web/Dockerfile
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${GIT_PORT}:${GIT_PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GIT_PORT=${GIT_PORT}
      - ORIGIN=${ORIGIN}:${WEB_PORT}
    volumes:
      - ./repo:/app/repo
    depends_on:
      - db
    restart: unless-stopped
